/*
 * settings.h
 *
 *  Created on: Apr 7, 2019
 *      Author: shaddy
 */

#ifndef SETTINGS_H_
#define SETTINGS_H_

#define DEBUG 1
#define ON_BUTTON_PIN 2
#define CANCEL_BUTTON_PIN 3
#define LED_PIN 4
#define LED_PIN 13
#define TURN_ON_PIN 10
#define HOME_PIN 5

#define TIME_MULTIPLIER 1000


#define TIME_TO_WAIT_HOME 30 * 60 * TIME_MULTIPLIER
//#define TIME_TO_WAIT_HOME 1 * 60
#define TIME_TO_OFF 30 * TIME_MULTIPLIER
#define TIME_LED 2 * TIME_MULTIPLIER
#define TIME_TO_FORCE 4 * TIME_MULTIPLIER
#define TIME_TO_ENABLE 10 * TIME_MULTIPLIER


#define ENABLE_BLINK_INTERVAL 300;
#define ENABLE_BLINK_COUNTER 3;

#define TURNING_OFF_BLINK_INTERVAL 500;
#define TURNING_OFF_BLINK_COUNTER 10000;

#define GRACEFU_OFF_BLINK_INTERVAL 500;
#define GRACEFUL_OFF_BLINK_COUNTER 10000;




#endif /* SETTINGS_H_ */
